version: "3.7"

services:
  mariadb:
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - mariadb-volume:/var/lib/mysql # Use bind mount

  php:
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - ./:/var/www/html:cached

#  crond:
#    environment:
#      PHP_FPM_CLEAR_ENV: "no"
#    volumes:
#    - ./:/var/www/html:cached

  nginx:
    volumes:
    - ./:/var/www/html:cached
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`,`${PROJECT_BASE_URL2}`,`${PROJECT_BASE_URL3}`)"

  redis:
    container_name: "${PROJECT_NAME}_redis"
    image: wodby/redis:$REDIS_TAG

volumes:
  mariadb-volume:
