version: "3.7"

services:
  mariadb:
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - mariadb-volume:/var/lib/mysql # Use bind mount

  php:
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - ./:/var/www/html:cached

#  crond:
#    environment:
#      PHP_FPM_CLEAR_ENV: "no"
#    volumes:
#    - ./:/var/www/html:cached

  nginx:
    volumes:
    - ./:/var/www/html:cached

volumes:
  mariadb-volume:
