version: "3.7"

services:
  mariadb:
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - mariadb-volume:/var/lib/mysql # Use bind mount

  php:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - codebase:/var/www/html

  crond:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
    - codebase:/var/www/html

  nginx:
    volumes:
    - codebase:/var/www/html

volumes:
  codebase:
  mariadb-volume:
