version: "3.7"

services:
  mariadb:
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - mariadb-volume:/var/lib/mysql # Use bind mount

  php:
    environment:
      PHP_FPM_CLEAR_ENV: "no"
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S opensmtpd:25
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
#      COLUMNS: 80 # Set 80 columns for docker exec -it.
#      # Read instructions at https://wodby.com/docs/stacks/php/local/#xdebug
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_MODE: debug
#      PHP_IDE_CONFIG: serverName=my-ide
#      PHP_XDEBUG_IDEKEY: "my-ide"
#      PHP_XDEBUG_CLIENT_HOST: 172.17.0.1 # Linux
#      PHP_XDEBUG_CLIENT_HOST: host.docker.internal # Docker 18.03+ Mac/Win
#      PHP_XDEBUG_CLIENT_HOST: 10.0.75.1 # Windows, Docker < 18.03
#      PHP_XDEBUG_LOG: /tmp/php-xdebug.log
    volumes:
    - ./:/var/www/html:cached
    # Docker-sync for macOS users
#    - docker-sync-mygov:/var/www/html

#  crond:
#    environment:
#      PHP_FPM_CLEAR_ENV: "no"
#    volumes:
#    - ./:/var/www/html:cached
    # Docker-sync for macOS users
#    - docker-sync-mygov:/var/www/html

  nginx:
    volumes:
    - ./:/var/www/html:cached
    # Docker-sync for macOS users
#    - docker-sync-mygov:/var/www/html
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`,`${PROJECT_BASE_URL2}`,`${PROJECT_BASE_URL3}`,`${PROJECT_BASE_URL4}`,`${PROJECT_BASE_URL5}`)"

#  redis:
#    container_name: "${PROJECT_NAME}_redis"
#    image: wodby/redis:$REDIS_TAG

  solr:
    image: wodby/solr:$SOLR_TAG
    container_name: "${PROJECT_NAME}_solr"
    environment:
      SOLR_DEFAULT_CONFIG_SET: $SOLR_CONFIG_SET
      SOLR_HEAP: 1024m
    labels:
    - "traefik.http.services.${PROJECT_NAME}_solr.loadbalancer.server.port=8983"
    - "traefik.http.routers.${PROJECT_NAME}_solr.rule=Host(`solr.${PROJECT_BASE_URL}`)"

volumes:
  mariadb-volume:
  # Docker-sync for macOS users
#  docker-sync-mygov:
#    external: true
