<?php

/**
 * @file
 * Contains mygov_webform_site_registration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mygov_webform_site_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mygov_webform_site_registration module.
    case 'help.page.mygov_webform_site_registration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('MyGov Webform Site Registration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mygov_webform_site_registration_theme() {
  return [
    'mygov_webform_site_registration' => [
      'render element' => 'children',
    ],
  ];
}
