<?php

/**
 * @file
 * Contains mygov_webform_site_registration.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mygov_webform_site_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mygov_webform_site_registration module.
    case 'help.page.mygov_webform_site_registration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('MyGov Webform Site Registration') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mygov_webform_site_registration_theme() {
  return [
    'mygov_webform_site_registration' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_webform_submission_form_alter().
 */
function mygov_webform_site_registration_webform_submission_form_alter(array &$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, 'site_registration')) {
    $site_name = $form['elements']['site_name']['#default_value'];
    $county_id = $form['elements']['county_name']['#default_value'];
  }
}
