<?php

/**
 * @file
 * Contains mygov_webform.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mygov_webform_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mygov_webform module.
    case 'help.page.mygov_webform':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds functionality to register new Domain sites based on county.') . '</p>';
      return $output;

    default:
  }
}
