<?php

namespace Drupal\mygov_registration\Form;

use Drupal\Core\Config\ConfigFactoryInterface;
use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

/**
 * Class MyGovRegistrationSettingsForm
 *
 * @package Drupal\mygov_registration\Form
 */
class MyGovRegistrationSettingsForm extends ConfigFormBase {

  protected function getEditableConfigNames() {
    return ['mygov_registration.settings'];
  }

  public function getFormId() {
    return 'mygov_registration_settings';
  }

  public function __construct(ConfigFactoryInterface $config_factory) {
    parent::__construct($config_factory);
  }

  public static function create(ContainerInterface $container) {
    return parent::create($container); // TODO: Change the autogenerated stub
  }

  public function buildForm(array $form, FormStateInterface $form_state) {
    return parent::buildForm($form, $form_state); // TODO: Change the autogenerated stub
  }

  public function submitForm(array &$form, FormStateInterface $form_state) {
    parent::submitForm($form, $form_state); // TODO: Change the autogenerated stub
  }

}
