name: CI

on:
  push:
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - '*'

  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # See also https://docs.docker.com/docker-hub/builds/
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_REPO_NAME: mygov
      IMAGE_NAME: drupal-php
      VERSION: 7.4

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:$VERSION

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker push $DOCKERHUB_REPO_NAME/$IMAGE_NAME:$VERSION
